### ISSUE TITLE
master requires newer boost version

### ISSUE THREAD

**Issue by fiedl** [fiedl/icecube-combo-install#5]
After changing the source from svn to github, I've noticed that the current master does not build on ubuntu 18.04. As it does on macOS, the error looks like this might be a boost version issue:

https://github.com/fiedl/icecube-combo-install/runs/470161968?check_suite_focus=true

```
../lib/libicetray.so: undefined reference to `boost::re_detail_106900::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
2303
../lib/libicetray.so: undefined reference to `boost::iostreams::detail::bzip2_base::end(bool, std::nothrow_t)'
2304
../lib/libicetray.so: undefined reference to `boost::re_detail_106900::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find()'
2305
clsim/CMakeFiles/clsim-convert_safeprimes.dir/build.make:106: recipe for target 'bin/clsim-convert_safeprimes' failed
```

[![Bildschirmfoto 2020-02-26 um 17 30 17](https://user-images.githubusercontent.com/1679688/75365583-afd11580-58bd-11ea-9524-d9815a44b2aa.png)](https://github.com/fiedl/icecube-combo-install/actions/runs/45601339)

Maybe try updating boost on ubuntu.

**Comment by fiedl** [comment]
Update boost: Easier said than done on ubuntu 18.04. The package sources have boost 1.6. The macOS install already uses 1.7. There are a couple of ppas. But they are also several versions behind.

Let's try to use homebrew for linux to get the latest boost.
